CREATE TABLE currencies (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        code VARCHAR(3) NOT NULL,
        name VARCHAR(50) NOT NULL,
        PRIMARY KEY (id)
);

ALTER TABLE cards ADD FOREIGN KEY (currency_id) REFERENCES currencies (id);
ALTER TABLE transactions ADD FOREIGN KEY (currency_id) REFERENCES currencies (id);